jclklib: solve libptpmgmt dependancy issue
Avoid pointing to ptpmgmt because user might not yet install it:
connect.cpp:23:10: fatal error: ptpmgmt/init.h: No such file or directory
   23 | #include <ptpmgmt/init.h>
      |          ^~~~~~~~~~~~~~~~

Signed-off-by: Song Yoong Siang <yoong.siang.song@intel.com>